### ISSUE TITLE
Win上搜索不到手机

### ISSUE THREAD

**Issue by soytony** [xiejinpeng007/X-Mokee-WrapShare#1]
请问一下，即使在手机上打开了“可发现”设置，win设备上还是搜索不到。
这个后期还会解决吗:-)

**Comment by xiejinpeng007** [comment]
@clicheeeeee 
我身边没有用来测试的 windows 设备所以没有去确认，如果有时间和设备会看看能不能处理。

**Comment by xiejinpeng007** [comment]
在魔趣论坛看了一下，只能从 Android 传到 Win。

**Comment by soytony** [comment]
明白了，感谢回复。
